# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.4.2"

gem "rails", "8.0.1"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets", "~> 4.0"
gem "sprockets-rails", "~> 3.4"

# Use pg as the database for Active Record
gem "pg", "~> 1.4"

# Use PostgreSQL's full text search
gem "pg_search", "~> 2.3"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 7.2"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder", "~> 2.11"

# Use Redis adapter to run Action Cable in production
gem "redis", "~> 5.0"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", "~> 1.15", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
gem "image_processing", "~> 1.2"

group :development, :test do
  gem "factory_bot_rails", "~> 6.4.0" # Remove the patch version after a new version fixes https://github.com/thoughtbot/factory_bot_rails/issues/433
  gem "pry", "~> 0.14"
  gem "rspec-rails", "~> 7.0"
  gem "knapsack_pro", "~> 8.0"
end

group :development do
  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  gem "erb_lint", "~> 0.3", require: false

  gem "rubocop-performance", "~> 1.24.0"
  gem "rubocop-rails", "~> 2.30.0"
  gem "rubocop-rspec", "~> 3.5.0"
  gem "rubocop-rake", "~> 0.7.0"
  gem "rubocop", "~> 1.74.0"
end

group :test do
  gem "capybara", "~> 3.38"
  gem "rails-controller-testing", "~> 1.0"
  gem "rspec-sidekiq", "~> 5.0"
  gem "rspec-retry", "~> 0.6"
  gem "selenium-webdriver", "~> 4.29.0"
  gem "shoulda-matchers", "~> 6.0"
  gem "webmock", "~> 3.18", require: "webmock/rspec"
  gem "vcr", "~> 6.1"
  gem "puffing-billy", "~> 4.0", require: "billy/capybara/rspec"
  gem "capybara_accessible_selectors", github: "citizensadvice/capybara_accessible_selectors",
                                       ref: "161b8c5b1a0a5408af914d7544956372e9da2c9e"
  gem "rspec-github", "~> 3.0.0", require: false
  gem "super_diff", "~> 0.15.0", require: "super_diff/rspec-rails"
end

gem "faker", "~> 3.1"

gem "prawn", "~> 2.5", require: false

gem "httparty", "~> 0.24"

gem "devise", "~> 5.0"

gem "administrate", "~> 0.18"

gem "dotenv-rails", "~> 3.0"

gem "devise_invitable", "~> 2.0"

gem "money", "~> 6.16"

if ENV["FLEXILE_SIDEKIQ_PRO_DISABLED"] == "true"
  gem "sidekiq", "~> 8"
else
  gem "sidekiq-pro", "~> 7", source: "https://gems.contribsys.com/"
end

gem "aws-sdk-s3", "~> 1.208"

gem "paper_trail", "~> 16.0"

gem "premailer-rails", "~> 1.12"

gem "js-routes", "~> 2.2"

gem "rack-cors", "~> 2.0"

gem "bugsnag", "~> 6.25"

gem "pagy", "~> 9.0"

gem "maxmind-geoip2", "~> 1.1"

gem "sidekiq-cron", "~> 2.4"

gem "stripe", "~> 13.5"

gem "flipper", "1.3.4"

gem "flipper-redis", "1.3.4"

gem "flipper-ui", "1.3.4"

gem "clearbit", "~> 0.3"

gem "oauth2", "~> 2.0"

gem "slack-notifier", "~> 2.4"

gem "color", "~> 1.8"

gem "rubyXL", "~> 3.4"

gem "countries", "~> 7.0"

gem "grover", "~> 1.1"

gem "dalli", "~> 3.2"

gem "jwt", "~> 2.10"

gem "hexapdf", "~> 1.2.0"

gem "redlock", "~> 2.0"

gem "ruby-openai", "~> 7.0"

gem "google-apis-oauth2_v2", "~> 0.18.0"

gem "csv", "~> 3.3"

gem "nanoid", "~> 2.0"

gem "json-schema", "~> 5.0"

gem "timecop", "~> 0.9", require: false

gem "resend", "~> 0.18.0"

gem "pundit", "~> 2.4"

gem "clerk-sdk-ruby", "~> 4.0", require: "clerk"
